services:
 
  #######################################
  # Traefik: The API Gateway
  #######################################
  macula-cloud-traefik:
    image: traefik
    container_name: macula-cloud-traefik
    restart: always
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - /var/run/docker.sock:/var/run/docker.sock