services:

  # deepseek          
  macula-cloud-deepseek:
    image: ollama/ollama:latest
    ports:
      - "11501:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_MODEL=deepseek-r1:8b
      # - OLLAMA_MODEL=deepseek-r1:14b
    volumes:
      - ${DEEPSEEK_HOME}/data/ollama:/root/.ollama
      - ${DEEPSEEK_HOME}/deepseek/entrypoint.sh:/root/.ollama/entrypoint.sh
    restart: unless-stopped
    entrypoint: ["/usr/bin/bash", "/root/.ollama/entrypoint.sh"]

  # open-webui
  macula-cloud-open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "53000:8080"
    volumes:
      - ${DEEPSEEK_HOME}/data/open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://macula-cloud-deepseek:11434
    restart: unless-stopped