version: "3"

networks:
  default:
    name: macula-cloud-network
    external: true

services:
 
  #######################################
  # Kong database migration
  #######################################
  macula-cloud-kong-migration:
    image: kong:latest
    container_name: macula-cloud-kong-migration
    command: "kong migrations bootstrap"
    restart: on-failure
    environment:
      - KONG_PG_HOST=macula-cloud-postgres
      - KONG_DATABASE=kong
      - KONG_PG_USER=${POSTGRES_USER}
      - KONG_PG_PASSWORD=${POSTGRES_PWD}

  #######################################
  # Kong: The API Gateway
  #######################################
  macula-cloud-kong:
    image: kong:latest
    container_name: macula-cloud-kong
    restart: always
    environment:
      - KONG_PG_HOST=macula-cloud-postgres
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_DATABASE=kong
      - KONG_PG_USER=${POSTGRES_USER}
      - KONG_PG_PASSWORD=${POSTGRES_PWD}
      - KONG_PROXY_ACCESS_LOG=/kong/access.log
      - KONG_PROXY_ACCESS_LOG=/usr/local/kong/logs/proxy_access.log
      - KONG_ADMIN_ACCESS_LOG=/usr/local/kong/logs/admin_access.log
      - KONG_PROXY_ERROR_LOG=/usr/local/kong/logs/proxy_error.log
      - KONG_ADMIN_ERROR_LOG=/usr/local/kong/logs/admin_error.log
    depends_on:
      - macula-cloud-kong-migration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://macula-cloud-kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8001:8001"
      - "8000:8000"
      - "8443:8443"
    volumes:
      - ${KONG_HOME}/conf/kong.conf:/etc/kong/kong.conf
      - ${KONG_HOME}/logs:/usr/local/kong/logs

  #######################################
  # Konga database prepare
  #######################################
  macula-cloud-konga-prepare:
    image: pantsel/konga:next
    container_name: macula-cloud-konga-prepare
    command: "-c prepare -a postgres -u postgresql://${POSTGRES_USER}:${POSTGRES_PWD}@macula-cloud-postgres:5432/kong"
    restart: on-failure

  #######################################
  # Konga: Kong GUIs
  #######################################
  macula-cloud-kong-admin:
    image: pantsel/konga:latest
    container_name: macula-cloud-kong-admin
    restart: always
    environment:
      - DB_ADAPTER=postgres
      - DB_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PWD}@macula-cloud-postgres:5432/kong
      - TOKEN_SECRET=km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      - NODE_ENV=production
    ports:
      - "1337:1337"
