version: "3"

networks:
  default:
    name: macula-cloud-network
    external: true

services:

  # Nacos registry
  macula-cloud-nacos:
    image: nacos/nacos-server:v2.2.1
    container_name: macula-cloud-nacos
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
      - 9555:9555
    environment:
      - TZ=Asia/Shanghai
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=macula-cloud-mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=${DB_USER}
      - MYSQL_SERVICE_PASSWORD=${DB_PWD}
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      - JVM_XMS=256m
      - JVM_XMX=512m