version: "3"

networks:
  default:
    name: macula-cloud-network
    external: true

services:
  macula-debezium-connect:
    container_name: macula-debezium-connect
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    ports:
      - "8083:8083"
    volumes:
    # SQLServer连接是报SSL错误，需要替换java.security
    - ${DEBEZIUM_HOME}/java/java.security:/etc/java/java-11-openjdk/java-11-openjdk-11.0.18.0.10-1.fc37.x86_64/conf/security/java.security
    # Mongo Sink
    - ${DEBEZIUM_HOME}/kafka-connect-mongodb/lib:/kafka/connect/kafka-connect-mongodb
    # Logs
    - ${DEBEZIUM_HOME}/logs:/kafka/logs
    environment:
      - BOOTSTRAP_SERVERS=macula-cloud-kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=debezium_connect_configs
      - OFFSET_STORAGE_TOPIC=debezium_connect_offsets
      - STATUS_STORAGE_TOPIC=debezium_connect_statuses
      - ENABLE_DEBEZIUM_KC_REST_EXTENSION=true
      - ENABLE_DEBEZIUM_SCRIPTING=true
      - CONNECT_REST_EXTENSION_CLASSES=io.debezium.kcrestextension.DebeziumConnectRestExtension

  macula-debezium-ui:
    container_name: macula-debezium-ui
    image: quay.io/debezium/debezium-ui:${DEBEZIUM_VERSION}
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CONNECT_URIS=http://macula-debezium-connect:8083
    depends_on:
      - macula-debezium-connect

