version: "3"

services:
  macula-cloud-mongo:
    container_name: macula-cloud-mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ${MONGO_HOME}/data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}

  macula-cloud-mongo-express:
    container_name: macula-cloud-mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - macula-cloud-mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME = ${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PWD}
      - ME_CONFIG_MONGODB_URL= mongodb://${MONGO_USER}:${MONGO_PWD}@macula-cloud-mongo:27017/
