version: "3"

services:

  # OnlyOffice
  macula-cloud-onlyoffice:
    image: onlyoffice/documentserver-ee:${ONLYOFFICE_VERSION}
    container_name: macula-cloud-onlyoffice
    restart: always
    ports:
      - 8600:80
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - JWT_ENABLED=false
    volumes:
      - ${ONLYOFFICE_HOME}/config/local.json:/etc/onlyoffice/documentserver/local.json
      - ${ONLYOFFICE_HOME}/logs:/var/log/onlyoffice
      - ${ONLYOFFICE_HOME}/data:/var/www/onlyoffice/Data
      - ${ONLYOFFICE_HOME}/lib:/var/lib/onlyoffice
      - ${ONLYOFFICE_HOME}/db:/var/lib/postgresql
