version: "3"

networks:
  default:
    external:
      name: macula-cloud-network

services:

  # Redis
  macula-cloud-redis:
    image: redis:latest
    container_name: macula-cloud-redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${REDIS_HOME}/conf:/usr/local/etc/redis
      - ${REDIS_HOME}/data:/data
    command: redis-server --appendonly yes

  # Mysql
  macula-cloud-mysql:
    image: mysql:5.7
    container_name: macula-cloud-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=macula-cloud
      - MYSQL_ROOT_PASSWORD=${DB_PWD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASS=${DB_PWD}
    volumes:
      - ${MYSQL_HOME}/data:/var/lib/mysql
      - ${MYSQL_HOME}/conf/my.cnf:/etc/my.cnf:ro
      - ${MYSQL_HOME}/sql:/docker-entrypoint-initdb.d

  # Rocket MQ
  macula-cloud-rocketmq-server:
    image: foxiswho/rocketmq:4.8.0
    container_name: macula-cloud-rocketmq-server
    restart: always
    ports:
      - 9876:9876
    volumes:
      - ${ROCKETMQ_HOME}/data/logs:/opt/logs
      - ${ROCKETMQ_HOME}/data/store:/opt/store
    environment:
      - JAVA_OPT_EXT=-Xms256M -Xmx512M -Xmn128m
    command: ["sh", "mqnamesrv"]

  macula-cloud-rocketmq-broker:
    image: foxiswho/rocketmq:4.8.0
    container_name: macula-cloud-rocketmq-broker
    restart: always
    depends_on:
      - macula-cloud-rocketmq-server
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ${ROCKETMQ_HOME}/data/logs:/opt/logs
      - ${ROCKETMQ_HOME}/data/store:/opt/store
      - ${ROCKETMQ_HOME}/conf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      - JAVA_OPT_EXT=-Xms256M -Xmx512M -Xmn128m
    command:
      - /bin/sh
      - -c
      - |
        rm -f broker1.conf
        cp /etc/rocketmq/broker.conf broker1.conf 
        echo "brokerIP1=${HOST_IP}" >> broker1.conf
        mqbroker -c broker1.conf -n macula-cloud-rocketmq-server:9876 autoCreateTopicEnable=true
