version: "3"

networks:
  default:
    name: macula-cloud-network
    external: true

services:

  # Nacos registry
  macula-cloud-nacos:
    image: nacos/nacos-server:v2.2.1
    container_name: macula-cloud-nacos
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
      - 9555:9555
    environment:
      - TZ=Asia/Shanghai
      - MODE=standalone
      - NACOS_AUTH_TOKEN=8b92c609089f74db3c5ee04bd7d4d89e8b92c609089f74db3c5ee04bd7d4d89e
      - NACOS_AUTH_IDENTITY_KEY=macula
      - NACOS_AUTH_IDENTITY_VALUE=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYWN1bGEtY2xvdWQiOlt7Im1hY3VsYSI6ImNsb3VkIn1dLCJpYXQiOjE2Nzk5OTc0NjYsImV4cCI6MTkwMDg1NzU5OSwiYXVkIjoiIiwiaXNzIjoiIiwic3ViIjoiIn0.6ck3z41Ph06cH8QE70uPZYM8p2ae_BNGPE-suOChHUs
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=macula-cloud-mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=${MYSQL_USER}
      - MYSQL_SERVICE_PASSWORD=${MYSQL_PWD}
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      - JVM_XMS=256m
      - JVM_XMX=512m