version: "3"

networks:
    default:
        external:
            name: macula-cloud-network

services:
    # oauth2
    macula-cloud-oauth2:
        image: registry.cn-shanghai.aliyuncs.com/macula-cloud/macula-cloud-oauth2:latest
        restart: always
        links:
            - macula-cloud-redis
            - macula-cloud-mysql
            - macula-cloud-eureka
        ports:
            - 7080:7080
        environment:
            EUREKA_SERVER: http://macula:macula2019@macula-cloud-eureka:8000/eureka/
            SPRING_REDIS_HOST: macula-cloud-redis
            SPRING_REDIS_PASSWORD: ${REDIS_PWD}
            SPRING_REDIS_DATABASE: 1
            SPRING_DATASOURCE_URL: ${PAAS_DB}
            SPRING_DATASOURCE_USERNAME: ${DB_USER}
            SPRING_DATASOURCE_PASSWORD: ${DB_PWD}
            SPRING_JPA_HIBERNATE_DDLAUTO: update
            SERVER_PORT: 7080
            MANAGER_SERVER_PORT: 9080
            SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: "false"

    # gateway
    macula-cloud-gateway:
        image: registry.cn-shanghai.aliyuncs.com/macula-cloud/macula-cloud-gateway:latest
        restart: always
        links:
            - macula-cloud-redis
            - macula-cloud-mysql
            - macula-cloud-eureka
            - macula-cloud-oauth2
        ports:
            - 8080:8080
        environment:
            EUREKA_SERVER: http://macula:macula2019@macula-cloud-eureka:8000/eureka/
            SPRING_REDIS_HOST: macula-cloud-redis
            SPRING_REDIS_PASSWORD: ${REDIS_PWD}
            SPRING_REDIS_DATABASE: 1
            SPRING_DATASOURCE_URL: ${PAAS_DB}
            SPRING_DATASOURCE_USERNAME: ${DB_USER}
            SPRING_DATASOURCE_PASSWORD: ${DB_PWD}
            SPRING_JPA_HIBERNATE_DDLAUTO: update
            SERVER_PORT: 8080
            MANAGER_SERVER_PORT: 9080
            OAUTH_URL: ${OAUTH_URL}
            SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED: "false"
