version: "3"

networks:
  default:
    name: macula-cloud-network
    external: true

services:

  # Jenkins
  macula-cloud-jenkins:
    image: jenkins/jenkins:lts
    container_name: macula-cloud-jenkins
    restart: always
    privileged: true
    user: root
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ${JENKINS_HOME}/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MAVEN_REPO}:/root/.m2
    ports:
      - "8888:8080"
      - "51000:50000"