version: "3"

networks:
  default:
    name: macula-cloud-network
    external: true

services:

  # Redis
  macula-cloud-redis:
    image: redis:latest
    container_name: macula-cloud-redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${REDIS_HOME}/conf:/usr/local/etc/redis
      - ${REDIS_HOME}/data:/data
    command: redis-server --appendonly yes

  # Mysql
  macula-cloud-mysql:
    image: mysql:latest
    container_name: macula-cloud-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=macula-cloud
      - MYSQL_ROOT_PASSWORD=${DB_PWD}
    volumes:
      - ${MYSQL_HOME}/data:/var/lib/mysql
      - ${MYSQL_HOME}/conf/my.cnf:/etc/my.cnf:ro
      - ${MYSQL_HOME}/sql:/docker-entrypoint-initdb.d