services:

  # OnlyOffice
  macula-cloud-onlyoffice:
    image: onlyoffice/documentserver-ee:${ONLYOFFICE_VERSION}
    container_name: macula-cloud-onlyoffice
    restart: always
    ports:
      - 8600:80
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - JWT_ENABLED=false
    volumes:
      - ${ONLYOFFICE_HOME}/config/default.json:/etc/onlyoffice/documentserver/default.json
      - ${ONLYOFFICE_HOME}/logs:/var/log/onlyoffice
      - ${ONLYOFFICE_HOME}/data/Data:/var/www/onlyoffice/Data
      - ${ONLYOFFICE_HOME}/data/lib:/var/lib/onlyoffice
      - ${ONLYOFFICE_HOME}/data/db:/var/lib/postgresql
      - ${ONLYOFFICE_HOME}/fonts:/usr/share/fonts