version: "3"

networks:
  default:
    name: macula-cloud-network
    external: true

services:

  # Nacos registry
  macula-cloud-nacos:
    image: nacos/nacos-server:v2.1.0
    container_name: macula-cloud-nacos
    restart: always
    ports:
      - 8848:8848
      - 9848:9848
      - 9555:9555
    environment:
      - TZ=Asia/Shanghai
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=macula-cloud-mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=${DB_USER}
      - MYSQL_SERVICE_PASSWORD=${DB_PWD}
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      - JVM_XMS=256m
      - JVM_XMX=512m

  # Sentinel dashboard
  macula-cloud-sentinel-dashboard:
    image: v-sentinel-dashboard
    container_name: macula-cloud-sentinel-dashboard
    restart: always
    build:
      context: ./sentinel-dashboard
      dockerfile: Dockerfile
    depends_on:
      - macula-cloud-nacos
    links:
      - macula-cloud-nacos
    ports:
      - 9080:8080
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms256m -Xmx512m -Dserver.port=8080 -Dcsp.sentinel.dashboard.server=localhost:8080 -Dproject.name=sentinel-dashboard -Dnacos.server.serverAddr=macula-cloud-nacos:8848 -Djava.security.egd=file:/dev/./urandom -Dcsp.sentinel.api.port=8719

  # Seata
  macula-cloud-seata-server:
    image: seataio/seata-server:latest
    container_name: macula-cloud-seata-server
    restart: always
    depends_on:
      - macula-cloud-nacos
    links:
      - macula-cloud-nacos
    ports:
      - 8091:8091
    volumes:
      - ${SEATA_HOME}/conf/registry.conf:/seata-server/resources/registry.conf
    environment:
      - TZ=Asia/Shanghai
      - SEATA_IP=${HOST_IP}
