version: "3"

services:
  # Canal Admin
  macula-cloud-canal-admin:
    image: canal/canal-admin:v1.1.6
    container_name: macula-cloud-canal-admin
    restart: always
    ports:
      - 8089:8089
    environment:
      - server.port=8089
      # - spring.datasource.address=macula-cloud-mysql:3306
      # - spring.datasource.username=${MYSQL_USER}
      # - spring.datasource.password=${MYSQL_PWD}
      - canal.adminUser=admin
      - canal.adminPasswd=admin
    volumes:
      - ${CANAL_HOME}/logs/admin/:/home/admin/canal-admin/logs

  # Canal Server
  macula-cloud-canal-server:
    image: canal/canal-server:v1.1.6
    container_name: macula-cloud-canal-server
    restart: always
    ports:
      - 11111:11111
    depends_on:
      - macula-cloud-canal-admin
    environment:
      - canal.auto.scan=true
      # instance settings
      - cana.destinations=example
      - canal.instance.master.address=macula-cloud-mysql:3306
      - canal.instance.dbUsername=${MYSQL_USER}
      - canal.instance.dbPassword=${MYSQL_PWD}
      - canal.instance.connectionCharset=UTF-8
      - canal.instance.tsdb.enable=true
      - canal.instance.gtidon=false
      - canal.instance.filter.regex=.*
      - canal.instance.detecting.enable=true
      - canal.instance.detecting.interval.time=3
      - canal.instance.detecting.retry.threshold=3
      - canal.instance.detecting.heartbeatHaEnable=true
      # admin settings
      - canal.admin.manager=macula-cloud-canal-admin:8089
      - canal.admin.port=11110
      - canal.admin.user=admin
      - canal.admin.passwd=4ACFE3202A5FF5CF467898FC58AAB1D615029441
      - canal.admin.register.auto=true
      # RocketMQ, Kafka
      - canal.serverMode=kafka #rocketmq, tcp, kafka
      - canal.mq.servers=macula-cloud-kafka:9092 #macula-cloud-rocketmq-server:9876
      - canal.mq.topic=example
      - canal.mq.partition=0
    volumes:
      - ${CANAL_HOME}/conf/canal.properties:/home/admin/canal-server/conf/canal.properties
      - ${CANAL_HOME}/conf/example:/home/admin/canal-server/conf/example
      - ${CANAL_HOME}/logs/server:/home/admin/canal-server/logs
