version: "3"

services:
  # Nginx
  macula-cloud-nginx:
    image: nginx:latest
    container_name: macula-cloud-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${NGINX_HOME}/conf/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_HOME}/cert:/etc/nginx/cert
      - ${NGINX_HOME}/html:/usr/share/nginx/html
      - ${NGINX_HOME}/logs:/var/log/nginx

  # Redis
  macula-cloud-redis:
    image: redis:latest
    container_name: macula-cloud-redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${REDIS_HOME}/conf:/usr/local/etc/redis
      - ${REDIS_HOME}/data:/data
    command: redis-server --appendonly yes --appendfsync always

  # Mysql
  macula-cloud-mysql:
    image: mysql:latest
    container_name: macula-cloud-mysql
    restart: always
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=macula-cloud
      - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
    volumes:
      - ${MYSQL_HOME}/data:/var/lib/mysql
      - ${MYSQL_HOME}/conf/my.cnf:/etc/my.cnf:ro
      - ${MYSQL_HOME}/sql:/docker-entrypoint-initdb.d
