version: "3"

networks:
  default:
    external:
      name: macula-cloud-network

services:
  # Zookeeper
  macula-cloud-zookeeper:
    image: wurstmeister/zookeeper
    container_name: macula-cloud-zookeeper
    restart: always
    ports:
      - 2181:2181
    volumes:
      - ${KAFKA_HOME}/data:/data

  # Kafka
  macula-cloud-kafka:
    image: wurstmeister/kafka
    container_name: macula-cloud-kafka
    restart: always
    depends_on:
      - macula-cloud-zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_IP}:9092
      KAFKA_CREATE_TOPICS: "example:2:0"
      KAFKA_ZOOKEEPER_CONNECT: macula-cloud-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - ${KAFKA_HOME}/logs:/kafka
