services:
  # Kafka https://hub.docker.com/r/bitnami/kafka
  macula-cloud-kafka:
    container_name: macula-cloud-kafka
    image: bitnami/kafka:3.6.2
    restart: always
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - ${KAFKA_HOME}:/bitnami/kafka
    environment:
      # KRaft settings
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@:9093
      # Listeners
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOST}:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Request
      - KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES=419430400
      # Memory
      - KAFKA_HEAP_OPTS=-Xmx1024m -Xms256m

  macula-cloud-kafka-ui:
    container_name: macula-cloud-kafka-ui
    image: provectuslabs/kafka-ui:master
    restart: always
    ports:
      - 9180:8080
    environment:
    - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=macula-cloud-kafka:9092