version: "3"

services:

  # Polaris https://hub.docker.com/r/polarismesh/polaris-standalone
  macula-cloud-polaris:
    image: polarismesh/polaris-standalone:latest
    container_name: macula-cloud-polaris
    restart: always
    ports:
      - 8080:8080
      - 8090:8090
      - 8091:8091
      - 8093:8093
      - 8761:8761
      - 9000:9000
      - 9090:9090
      - 15010:15010
    environment:
      - TZ=Asia/Shanghai
      - MODE=standalone