CREATE DATABASE `canal` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER canal IDENTIFIED BY 'canal';
GRANT SELECT,
    SHOW VIEW,
    REPLICATION SLAVE,
    REPLICATION CLIENT ON *.* TO 'canal' @'%';
FLUSH PRIVILEGES;